-- Generated from template

if MyGameMode == nil then
	_G.MyGameMode = class({})
end

require("statcollection/init")
require('gamemode')
require('utilities')
require('upgrades')
require('mechanics')
require('orders')
require('builder')
require('killbox')
require('abilities')
require('elementupgrade')

require("libraries/buildinghelper")
require('libraries/timers')
require('libraries/popups')
require('libraries/notifications')

require('unit_scripts/ai_shared_code')

function Precache( context )

	-- Model ghost and grid particles
	PrecacheResource("particle_folder", "particles/buildinghelper", context)
	PrecacheResource("particle_folder", "particles/econ/items/earthshaker/earthshaker_gravelmaw/", context)
	PrecacheResource("particle_folder", "particles/units/heroes/hero_luna.pcf", context)
	PrecacheResource("particle_folder", "particles/units/heroes/hero_winter_wyvern/", context)
	PrecacheResource("particle_folder", "particles/units/heroes/hero_nevermore/", context)
	PrecacheResource("particle_folder", "particles/units/heroes/hero_dragon_knight/", context)
	PrecacheResource("particle_folder", "particles/units/heroes/hero_kunkka/", context)
	PrecacheResource("particle_folder", "particles/units/heroes/hero_treant/", context)
	PrecacheResource("particle_folder", "particles/units/heroes/hero_earthshaker/", context)
	PrecacheResource("particle_folder", "particles/units/heroes/hero_sven/", context)
	PrecacheResource("particle_folder", "particles/units/heroes/hero_oracle/", context)

	-- Resources used
	PrecacheUnitByNameSync("npc_dota_hero_luna", context)
	PrecacheUnitByNameSync("tower", context)
	PrecacheUnitByNameSync("tower_tier2", context)
	PrecacheUnitByNameSync("cannon_tower", context)
	PrecacheUnitByNameSync("tower_fire", context)
	PrecacheUnitByNameSync("tower_water", context)
	PrecacheUnitByNameSync("tower_nature", context)
	PrecacheUnitByNameSync("tower_earth", context)
	PrecacheUnitByNameSync("tower_light", context)
	PrecacheUnitByNameSync("tower_dark", context)
	PrecacheUnitByNameSync("tower_fire_light_lightning", context)
	PrecacheUnitByNameSync("tower_water_light_speedaura", context)
	PrecacheUnitByNameSync("tower_dark_nature_multishot", context)
	PrecacheUnitByNameSync("tower_fire_dark_nevermore", context)
	PrecacheUnitByNameSync("tower_earth_light_damageaura", context)
	PrecacheUnitByNameSync("tower_earth_dark_bash", context)
	PrecacheUnitByNameSync("tower_water_dark_poison", context)
	PrecacheUnitByNameSync("tower_fire_nature_sniper", context)
	PrecacheUnitByNameSync("tower_water_earth_glaive", context)
	PrecacheUnitByNameSync("tower_fire_earth_gold", context)
	PrecacheUnitByNameSync("tower_earth_nature_critical", context)
	PrecacheUnitByNameSync("tower_water_nature_frost", context)
	PrecacheUnitByNameSync("tower_light_dark_impetus", context)
	PrecacheUnitByNameSync("tower_fire_water_decrepify", context)
	PrecacheUnitByNameSync("tower_light_nature_life", context)

	PrecacheUnitByNameSync("tower_fire2_light2_zeus", context)
	PrecacheUnitByNameSync("tower_water2_light2_speedaura2", context)
	PrecacheUnitByNameSync("tower_dark2_nature2_multishot2", context)
	PrecacheUnitByNameSync("tower_fire2_dark2_nevermore2", context)
	PrecacheUnitByNameSync("tower_earth2_light2_damageaura2", context)
	PrecacheUnitByNameSync("tower_earth2_dark2_bash2", context)
	PrecacheUnitByNameSync("tower_water2_dark2_poison2", context)
	PrecacheUnitByNameSync("tower_fire2_nature2_sniper2", context)
	PrecacheUnitByNameSync("tower_water2_earth2_glaive2", context)
	PrecacheUnitByNameSync("tower_fire2_earth2_gold2", context)
	PrecacheUnitByNameSync("tower_earth2_nature2_critical2", context)
	PrecacheUnitByNameSync("tower_water2_nature2_frost2", context)
	PrecacheUnitByNameSync("tower_light2_dark2_impetus2", context)
	PrecacheUnitByNameSync("tower_fire2_water2_decrepify2", context)
	PrecacheUnitByNameSync("tower_light2_nature2_life2", context)

	PrecacheUnitByNameSync("sell_building", context)
	PrecacheUnitByNameSync("fire_shop", context)
	PrecacheUnitByNameSync("water_shop", context)
	PrecacheUnitByNameSync("nature_shop", context)
	PrecacheUnitByNameSync("earth_shop", context)
	PrecacheUnitByNameSync("light_shop", context)
	PrecacheUnitByNameSync("dark_shop", context)
	PrecacheUnitByNameSync("creep_wave1", context)
	PrecacheUnitByNameSync("creep_wave2", context)
	PrecacheUnitByNameSync("creep_wave3", context)
	PrecacheUnitByNameSync("creep_wave4", context)
	PrecacheUnitByNameSync("creep_wave5", context)
	PrecacheUnitByNameSync("creep_wave6", context)
	PrecacheUnitByNameSync("creep_wave7", context)
	PrecacheUnitByNameSync("creep_wave8", context)
	PrecacheUnitByNameSync("creep_wave9", context)
	PrecacheUnitByNameSync("creep_wave10", context)
	PrecacheUnitByNameSync("creep_wave11", context)
	PrecacheUnitByNameSync("creep_wave12", context)
	PrecacheUnitByNameSync("creep_wave13", context)
	PrecacheUnitByNameSync("creep_wave14", context)
	PrecacheUnitByNameSync("creep_wave15", context)
	PrecacheUnitByNameSync("creep_wave16", context)
	PrecacheUnitByNameSync("creep_wave17", context)
	PrecacheUnitByNameSync("creep_wave18", context)
	PrecacheUnitByNameSync("creep_wave19", context)
	PrecacheUnitByNameSync("creep_wave20", context)
	PrecacheUnitByNameSync("creep_wave21", context)
	PrecacheUnitByNameSync("creep_wave22", context)
	PrecacheUnitByNameSync("creep_wave23", context)
	PrecacheUnitByNameSync("creep_wave24", context)
	PrecacheUnitByNameSync("creep_wave25", context)
	PrecacheUnitByNameSync("creep_wave26", context)
	PrecacheUnitByNameSync("creep_wave27", context)
	PrecacheUnitByNameSync("creep_wave28", context)
	PrecacheUnitByNameSync("creep_wave29", context)
	PrecacheUnitByNameSync("creep_wave30", context)
	PrecacheUnitByNameSync("creep_wave31", context)
	PrecacheUnitByNameSync("creep_wave32", context)
	PrecacheUnitByNameSync("creep_wave33", context)
	PrecacheUnitByNameSync("creep_wave34", context)
	PrecacheUnitByNameSync("creep_wave35", context)
	PrecacheUnitByNameSync("creep_wave36", context)
	PrecacheUnitByNameSync("creep_wave37", context)
	PrecacheUnitByNameSync("creep_wave37", context)
    PrecacheUnitByNameSync("creep_wave38", context)
    PrecacheUnitByNameSync("creep_wave39", context)
    PrecacheUnitByNameSync("creep_wave40", context)
    PrecacheUnitByNameSync("creep_wave50", context)
    PrecacheUnitByNameSync("creep_wave51", context)
    PrecacheUnitByNameSync("creep_wave52", context)
    PrecacheUnitByNameSync("creep_wave53", context)
    PrecacheUnitByNameSync("creep_wave54", context)
    PrecacheUnitByNameSync("creep_wave55", context)
    PrecacheUnitByNameSync("creep_wave56", context)
    PrecacheUnitByNameSync("creep_wave57", context)
    PrecacheUnitByNameSync("creep_wave58", context)
    PrecacheUnitByNameSync("creep_wave59", context)
    PrecacheUnitByNameSync("creep_wave_damage_test", context)

end

-- Create the game mode when we activate
function Activate()
    MyGameMode:InitGameMode()
end
